apiVersion: batch/v1
kind: Job
metadata:
  name: pi-hi
spec:
  template:
    metadata:
      annotations:
        lsf.queue: "priority"
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(10000)"]
      restartPolicy: Never
  backoffLimit: 4
  completions: 25
  parallelism: 25
